---
- name: Update The System
  apt:
    update_cache: yes
  become: yes

- name: Prerequisites Packages Installation
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add The GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add The Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes

- name: Docker Installation
  apt:
    name: docker-ce
    state: present
  become: yes

- name: Docker service Start
  service:
    name: docker
    state: started
  become: yes

- name: simple html create
  ansible.builtin.copy:
    content: "<html><body><h1>Hello from ansible-managed Nginx!</h1></body></html>"
    dest: /home/ansible/docker-nginx/index.html

- name: copy dockerfile to the node
  ansible.builtin.copy:
    src: /etc/ansible/tmp/docker-nginx/Dockerfile
    dest: /home/ansible/docker-nginx/Dockerfile

- name: docker image create
  community.docker.docker_image_build:
    name: my-nginx-image
    path: /home/ansible/docker-nginx
    dockerfile: Dockerfile

- name: Start container Nginx
  community.docker.docker_container:
    name: my-nginx-container
    image: my-nginx-image
    state: started
    ports:
      - "80:80"
